#!/bin/bash -e
name="GRUB Invaders"
binary=/boot/invaders

if test -e $binary ; then
  echo "Found $name: $binary" >&2
  basename=`basename $binary`
  dirname=`dirname $binary`
  grub_dirname=`echo ${dirname} | sed -e "s%^/boot%${GRUB_DRIVE_BOOT}%g"`

  cat << EOF
menuentry "$name" {
	multiboot	${grub_dirname}/${basename}
}
EOF
fi
