#!/bin/bash -e

if test -e /boot/invaders ; then
  source /usr/lib/grub/update-grub_lib
  INVADERSPATH=$( make_system_path_relative_to_its_root "/boot/invaders" )
  echo "Found GRUB Invaders image: /boot/invaders" >&2
  cat << EOF
menuentry "GRUB Invaders" {
EOF
  prepare_grub_to_access_device ${GRUB_DEVICE_BOOT} | sed -e "s/^/\t/g"
  cat << EOF
	multiboot	${INVADERSPATH}
}
EOF
fi
